name: "TFSEC to CWL"
description: "Send TFSEC report to CWL"
author: "Jacob Scheid"
inputs:
  report:
    description: "Report file to use"
    required: true
  aws_key_id:
    description: "AWS Key ID for writing to CWL"
    required: true
  aws_key_secret:
    description: "AWS Key Secret for writing to CWL"
    required: true
  github_token:
    description: "API Key for writing comments"
    required: true
  cwl_group:
    description: "Cloudwatch logs group"
    required: true
  cwl_stream:
    description: "Cloudwatch logs stream"
    required: true
outputs:
  rules:
    description: "Rules TFSec reported on"
runs:
  using: "docker"
  image: "Dockerfile"
