name: "TFSEC to CWL"
description: "Send TFSEC report to CWL"
author: "Jacob Scheid"
inputs:
  report:
    description: "Report file to use"
    required: true
outputs:
  rules:
    description: "Rules TFSec reported on"
runs:
  using: "docker"
  image: "Dockerfile"
